version: '3.9'

services:

  web:
    container_name: nginxsite 
    build: .
    image: nginxsite:0.0.1
    volumes:
      - ./templates:/etc/nginx/templates
    ports:
      - "80:80"
      - "8080:80"

  backend:
    image: openjdk:19-jdk-alpine3.16

