version: '3.9'

services:

  backend:
    image: openjdk:19-jdk-alpine3.16
    build: ./Spring/demo
    image: spring:0.0.1
    ports:
      - "8080:8080"

  web:
    container_name: nginxsite 
    build: ./Nginx
    image: nginxsite:0.0.1
    volumes:
      - ./templates:/etc/nginx/templates
    ports:
      - "80:80"
    depends_on:
      - backend
